version: "3.2"

services:
  app:
    image: briankalid/interaction-app:latest
    container_name: app
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/ec2-user/.env
        target: /src/src/core/.env
        read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
  
  streamlit-app:
    image: briankalid/streamlit-app:latest
    container_name: streamlit-app
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/ec2-user/.env
        target: /src/.env
        read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./deployment:/etc/nginx/conf.d:ro
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
