name: Build, Push, Deploy

on:
  push:
    branches: [ development ]

jobs:
  build_and_push:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    #   - name: Checkout the repository
    #     uses: actions/checkout@v4
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       ecr: auto
    #       logout: true
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    #   - name: Extract metadata (labels, tags, etc.) for Docker
    #     id: meta
    #     uses: docker/metadata-action@v5
    #     with:
    #       images: briankalid/interaction-app
    #   - name: Build and push Docker image
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: ./api/interaction
    #       file: ./api/interaction/Dockerfile
    #       push: true
    #       tags: briankalid/interaction-app:latest
    #       labels: ${{ steps.meta.outputs.labels }}
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
          configuration: DEBUG=0
          use-pro: 'true'
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
