- name: Start LocalStack
	uses: LocalStack/setup-localstack@main
	with:
		image-tag: 'latest'
		install-awslocal: 'true'
	configuration: DEBUG=1
		use-pro: 'true'
	env:
		LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
